env: Pendulum-v1

train:
  training_iterations: 2000
  min_batch_steps: 5000 # batch_size
  nb_critic_updates: 10
  exp_name: Pendulum_exp_22_001

agent:
  actor_lr: 0.001
  critic_lr: 0.01
  gamma: 0.99